version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.go
    ports:
      - "8080:8080"
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.node
  #   ports:
  #     - "5000:5000"
  # db: 
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres