basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is the API for the HereWeGo application.
  title: HereWeGo API
  version: 0.0.1
paths:
  /api/:
    get:
      consumes:
      - application/json
      description: Returns a hello world message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Returns a hello world message
      tags:
      - hello
swagger: "2.0"
